# Lambda Method

In [104]:
def method1(x):
    x = x ** 2
    print(x)

In [105]:
method1(4)

16


In [106]:
def method2(x):
    x = x ** 2
    return x

In [107]:
method2(4)

16

In [108]:
x = lambda y: y ** 2

In [109]:
x(2)

4

In [110]:
x = lambda a,b : a * b

x(20, 4)

# Numpy

In [111]:
import numpy as np

In [112]:
l = [1,2,3,4,5]

In [113]:
npa = np.array(l)

In [114]:
type(l), type(npa)

(list, numpy.ndarray)

In [115]:
npa.shape

(5,)

In [116]:
l.append('string')

In [117]:
npa = np.array(l)


In [118]:
npa

array(['1', '2', '3', '4', '5', 'string'], dtype='<U11')

In [119]:
l1 = [10,14, 15,14]

In [120]:
np.array(l +l1)

array(['1', '2', '3', '4', '5', 'string', '10', '14', '15', '14'],
      dtype='<U11')

In [121]:
l + 20

TypeError: can only concatenate list (not "int") to list

In [ ]:
l + [20]

In [ ]:
l = [[1,2],[2,5],[3,7]]

In [ ]:
npa2d = np.array(l)

In [129]:
npa2d

array([['1.0', '2.0'],
       ['2.0', '5.0'],
       ['3.0', '7.0']], dtype='<U32')

In [ ]:
npa2d.shape

In [ ]:
npa2d = np.array(l, dtype='float')

In [ ]:
npa2d

In [125]:
npa2d

array([['1.0', '2.0'],
       ['2.0', '5.0'],
       ['3.0', '7.0']], dtype='<U32')

  # Statistical Operations in Numpy

In [142]:
l = [[1,2],[2,5],[3,7]]

In [137]:
npa2d

array(['1', '2', '3', '4', '5', 'string'], dtype='<U11')

In [143]:
npa2d = np.array(l, dtype='float')

In [144]:
npa2d

array([[1., 2.],
       [2., 5.],
       [3., 7.]])

In [145]:
npa2d.mean()

3.3333333333333335

In [146]:
npa2d.min()

1.0

In [147]:
npa2d.max()

7.0

In [148]:
npa2d.var()

4.222222222222222

In [149]:
npa2d.std()

2.0548046676563256

In [152]:
np.median(npa2d)

2.5

# Shape, Reshape, Ravel and Flatten

In [153]:
npa2d

array([[1., 2.],
       [2., 5.],
       [3., 7.]])

In [154]:
npa2d.shape

(3, 2)

In [155]:
npa2d.reshape(2,3)

array([[1., 2., 2.],
       [5., 3., 7.]])

In [157]:
npa2d.reshape(1,6)

array([[1., 2., 2., 5., 3., 7.]])

In [158]:
npa2d.flatten()

array([1., 2., 2., 5., 3., 7.])

# Sequence, Repetitions and Random Numbers

In [159]:
np.arange(1,5, dtype='float')

array([1., 2., 3., 4.])

In [160]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [162]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [163]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [164]:
np.zeros([1,5])

array([[0., 0., 0., 0., 0.]])

In [165]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [166]:
np.ones([1,2])

array([[1., 1.]])

In [167]:
np.tile([1,2],3)

array([1, 2, 1, 2, 1, 2])

In [168]:
np.repeat([1,2],3)

array([1, 1, 1, 2, 2, 2])

In [170]:
np.random.rand(3,3)

array([[0.37375421, 0.44070655, 0.46879634],
       [0.61225706, 0.35912365, 0.6151828 ],
       [0.48866212, 0.59389283, 0.2828433 ]])

In [173]:
np.random.randint(0,10, [3,3])

array([[4, 9, 5],
       [3, 1, 0],
       [4, 4, 9]])

In [182]:
np.random.seed(1)
np.random.randint(0,10, [3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [183]:
np.unique(npa2d)

array([1., 2., 3., 5., 7.])

In [184]:
npa2d

array([[1., 2.],
       [2., 5.],
       [3., 7.]])

In [186]:
np.unique(npa2d, return_counts= True)

(array([1., 2., 3., 5., 7.]), array([1, 2, 1, 1, 1], dtype=int64))

# Where()

In [188]:
arr = np.array([8,2,15,23,15,56,59,29])

In [189]:
arr

array([ 8,  2, 15, 23, 15, 56, 59, 29])

In [190]:
np.where(arr >10)

(array([2, 3, 4, 5, 6, 7], dtype=int64),)

In [191]:
index = np.where(arr>10)
arr[index]

array([15, 23, 15, 56, 59, 29])

In [192]:
index = np.where(arr<10)
arr[index]

array([8, 2])

In [194]:
index = np.where(arr==8)
arr[index]

array([8])

In [195]:
arr >10

array([False, False,  True,  True,  True,  True,  True,  True])

In [196]:
arr[arr>10]

array([15, 23, 15, 56, 59, 29])

In [197]:
arr.max()

59

In [198]:
arr.argmax()

6

In [199]:
arr.argmin()

1

In [200]:
arr[arr.argmin()]

2

# File Read and Write

In [201]:
npa2d

array([[1., 2.],
       [2., 5.],
       [3., 7.]])

In [203]:
np.savetxt('npa2d.csv',npa2d, delimiter=',')

In [205]:
np.loadtxt('npa2d.csv',delimiter = ',')

array([[1., 2.],
       [2., 5.],
       [3., 7.]])

# Concatenate and Sorting

In [206]:
npa2d

array([[1., 2.],
       [2., 5.],
       [3., 7.]])

In [207]:
np.concatenate([npa2d, npa2d], axis =0)

array([[1., 2.],
       [2., 5.],
       [3., 7.],
       [1., 2.],
       [2., 5.],
       [3., 7.]])

In [209]:
np.concatenate([npa2d, npa2d], axis =1)

array([[1., 2., 1., 2.],
       [2., 5., 2., 5.],
       [3., 7., 3., 7.]])

In [210]:
np.concatenate([npa2d, arr], axis =0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [211]:
np.vstack([npa2d,npa2d])

array([[1., 2.],
       [2., 5.],
       [3., 7.],
       [1., 2.],
       [2., 5.],
       [3., 7.]])

In [213]:
npa = np.hstack([npa2d,npa2d])

In [214]:
npa.sort()

In [215]:
npa

array([[1., 1., 2., 2.],
       [2., 2., 5., 5.],
       [3., 3., 7., 7.]])

 # Working with Dates

In [216]:
d = np.datetime64('2021-12-04 23:34:24')

In [217]:
d

numpy.datetime64('2021-12-04T23:34:24')

In [218]:
d + 10

numpy.datetime64('2021-12-04T23:34:34')

In [219]:
oneday = np.timedelta64(1, 'D')

In [220]:
oneday

numpy.timedelta64(1,'D')

In [221]:
d+oneday

numpy.datetime64('2021-12-05T23:34:24')

In [223]:
onemin = np.timedelta64(1, 'm')

In [225]:
onemin

numpy.timedelta64(1,'m')

In [226]:
d + onemin

numpy.datetime64('2021-12-04T23:35:24')

# Pandas

In [228]:
import pandas as pd

In [230]:
data = {'fruite' :[1,2,3,4,5], 'veg': [6,7,8,9,10]}

In [231]:
data

{'fruite': [1, 2, 3, 4, 5], 'veg': [6, 7, 8, 9, 10]}

In [233]:
type(data)

dict

In [234]:
df = pd.DataFrame(data)

In [235]:
df

fruite  veg
0       1    6
1       2    7
2       3    8
3       4    9
4       5   10

In [236]:
df['fruite']

0    1
1    2
2    3
3    4
4    5
Name: fruite, dtype: int64

In [237]:
type(df['fruite'])

pandas.core.series.Series

In [238]:
df['veg']

0     6
1     7
2     8
3     9
4    10
Name: veg, dtype: int64

In [239]:
df.veg

0     6
1     7
2     8
3     9
4    10
Name: veg, dtype: int64

# Reading and Writing File

In [242]:
df = pd.read_csv('pandas/nba.csv')

In [243]:
df.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [244]:
df.tail()

Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler   
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [245]:
df.head(10)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8   Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   
9   Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5                NaN  12000000.0  
6                LSU   1170960.0  
7            Gonzaga   2165160.0  
8         Louisville   1824360.0  
9     Oklahoma State   3431040.0

In [247]:
df1 = df[['Name','Team']]

In [249]:
df1.head()

Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics

In [254]:
df = pd.read_csv('pandas/nba.csv', usecols =['Name','Team'])

In [255]:
df.head()

Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics

In [256]:
df.set_index('Name')

Team
Name                         
Avery Bradley  Boston Celtics
Jae Crowder    Boston Celtics
John Holland   Boston Celtics
R.J. Hunter    Boston Celtics
Jonas Jerebko  Boston Celtics
...                       ...
Shelvin Mack        Utah Jazz
Raul Neto           Utah Jazz
Tibor Pleiss        Utah Jazz
Jeff Withey         Utah Jazz
NaN                       NaN

[458 rows x 1 columns]

In [258]:
df.to_csv('pandas/df.csv')

# Info, Shape, Duplicated, Drop

In [259]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    457 non-null    object
 1   Team    457 non-null    object
dtypes: object(2)
memory usage: 7.3+ KB


In [260]:
df.describe()

Name                  Team
count            457                   457
unique           457                    30
top     Nik Stauskas  New Orleans Pelicans
freq               1                    19

In [261]:
df.shape

(458, 2)

In [263]:
df.duplicated().sum()

0

In [265]:
df.duplicated(subset =['Team']).sum()

427

In [270]:
df = df.append(df)

In [271]:
df.duplicated().sum()

1374

In [272]:
df.drop_duplicates()

Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz
457            NaN             NaN

[458 rows x 2 columns]

In [273]:
df.columns

Index(['Name', 'Team'], dtype='object')

In [274]:
df.columns = ['0','1']

In [276]:
df.columns = ['Name','Team']

In [278]:
df.rename(columns = {'Name': 'name', 'Team':'team'})

name            team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz
457            NaN             NaN

[1832 rows x 2 columns]

# NAN and NULL Value

In [279]:
df = pd.read_csv('pandas/IMDB-Movie-Data.csv')

In [280]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [282]:
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [283]:
df.isna().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [284]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Title               1000 non-null   object 
 2   Genre               1000 non-null   object 
 3   Description         1000 non-null   object 
 4   Director            1000 non-null   object 
 5   Actors              1000 non-null   object 
 6   Year                1000 non-null   int64  
 7   Runtime (Minutes)   1000 non-null   int64  
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64  
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB


In [285]:
df1 = df.dropna()

In [286]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 838 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                838 non-null    int64  
 1   Title               838 non-null    object 
 2   Genre               838 non-null    object 
 3   Description         838 non-null    object 
 4   Director            838 non-null    object 
 5   Actors              838 non-null    object 
 6   Year                838 non-null    int64  
 7   Runtime (Minutes)   838 non-null    int64  
 8   Rating              838 non-null    float64
 9   Votes               838 non-null    int64  
 10  Revenue (Millions)  838 non-null    float64
 11  Metascore           838 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 85.1+ KB


In [287]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [290]:
df1 =df.dropna(axis =1)

In [293]:
df1.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  
0     8.1  757074  
1     7.0  485820  
2     7.3  157606  
3     7.2   60545  
4     6.2  393727

# Imputation

In [295]:
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [297]:
df1 = df.fillna(0)

In [298]:
df1.isnull().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

In [299]:
df.fillna('mean').head(2)

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   

                                         Description      Director  \
0  A group of intergalactic criminals are forced ...    James Gunn   
1  Following clues to the origin of mankind, a te...  Ridley Scott   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   

   Rating   Votes Revenue (Millions) Metascore  
0     8.1  757074             333.13        76  
1     7.0  485820             126.46        65

In [302]:
revenue = df['Revenue (Millions)']
revenue

0      333.13
1      126.46
2      138.12
3      270.32
4      325.02
        ...  
995       NaN
996     17.54
997     58.01
998       NaN
999     19.64
Name: Revenue (Millions), Length: 1000, dtype: float64

In [304]:
mean1 = revenue.mean()
mean1

82.95637614678897

In [310]:
revenue =revenue.fillna(mean1)

In [311]:
df['Revenue (Millions)'] = revenue

In [312]:
df.isnull().sum()

Rank                   0
Title                  0
Genre                  0
Description            0
Director               0
Actors                 0
Year                   0
Runtime (Minutes)      0
Rating                 0
Votes                  0
Revenue (Millions)     0
Metascore             64
dtype: int64

In [314]:
x = lambda a : a*a
x(4)

16

In [317]:
mean_meta = df['Metascore'].mean()
mean_meta

58.98504273504273

In [320]:
meta = df['Metascore'].apply(lambda x: x if x == x else mean_meta)
meta

0      76.0
1      65.0
2      62.0
3      59.0
4      40.0
       ... 
995    45.0
996    46.0
997    50.0
998    22.0
999    11.0
Name: Metascore, Length: 1000, dtype: float64

In [321]:
meta.isnull().sum()

0